#Uses custom Structure type. (custom structure type has more spawn checks and allows bigger cities (size and maxDistance), but may have some generation issues when using /locate or /place)
UseCustomStructureType = true
#--------------------------------------------City Settings--------------------------------------------
#Будут ли в городах машины
SpawnCars = true
#Отключает генерацию спавнеров монстров в структуре города.
DisableSpawners = false
#Это ограничение глубины jigsaw-структур с максимумом 30 элементов.
#Range: 1 ~ 30
CitySize = 15
#Определяет максимальное расстояние любого элемента от начальной точки структуры.
#Range: 1 ~ 1000
CityDistanceFromCenter = 128
#--------------------------------------------City Spawn Settings--------------------------------------------
#Среднее расстояние между двумя соседними попытками генерации.
#Range: 0 ~ 4096
CitySpacing = 34
#Минимальное расстояние между двумя соседними попытками.
#Range: 0 ~ 4096
CitySeparation = 8
#defines step of structure spawn ('step' in default structure.json)
CityStep = "surface_structures"
#defines terrain adaptation of structure spawn ('terrain_adaptation' in default structure.json)
CityTerrainAdaptation = "beard_thin"
#defines start height adaptation of structure spawn ('start_height' in default structure.json)
CityStartHeight = "\"absolute\": 10\n"
#defines project start to heightmap of structure spawn ('project_start_to_heightmap' in default structure.json)
CityProjectStartToHeightmap = "OCEAN_FLOOR"
#Биомы в которых будут появляться города.
CityBiomes = ["plains", "snowy_plains", "sunflower_plains", "snowy_plains", "desert"]
#--------------------------------------------Villages City Spawn Settings--------------------------------------------
#Биомы в которых будут появляться города.
VillagesCityBiomes = ["taiga", "plains", "snowy_plains", "sunflower_plains", "snowy_taiga"]
#Минимальное расстояние между двумя соседними попытками.
#Range: 0 ~ 4096
VillagesCitySeparation = 16
#Среднее расстояние между двумя соседними попытками генерации.
#Range: 0 ~ 4096
VillagesCitySpacing = 34

